DROP TABLE IF EXISTS PERSON_INPUT;
DROP TABLE IF EXISTS PERSON_OUTPUT;

CREATE TABLE PERSON_INPUT (
    id INT PRIMARY KEY,
    firstName VARCHAR(255),
    lastName VARCHAR(255)
);

CREATE TABLE PERSON_OUTPUT (
    firstName VARCHAR(255),
    lastName VARCHAR(255)
);
